version: '3.9'
services:
  nginx:
    image: nginx
    ports:
      - 8001:80
    volumes:
      - .:/public_html
      - .:/etc/nginx/conf.d
    networks:
      - nginx_php
  
  php:
    image: php:fpm-alpine
    volumes:
    - .:/public_html
    expose:
      - 9000
    networks:
    - nginx_php

networks:
  nginx_php:
